import * as dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  FRONTEND_URL,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  AWS_REGION,
  AWS_COGNITO_DOMAIN,
  AWS_COGNITO_USER_POOL_ID,
  AWS_COGNITO_CLIENT_ID,
  AWS_COGNITO_CLIENT_SECRET,
  AWS_COGNITO_CALLBACK_URL,
  AWS_COGNITO_LOGOUT_URL,
  AWS_SES_FROM_EMAIL,
  AWS_SES_ACCESS_KEY,
  AWS_SES_SECRET_KEY,
  COGNITO_JWT_PUBLIC_KEY_URL,

} = process.env;