name: Deploy Server to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENV_CONTENTS: ${{ secrets.ENV_CONTENTS }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} bash -s <<EOF
          cd /home/ec2-user/daily-retrospect-backend

          git remote set-url origin https://${GH_TOKEN}@github.com/dnslfkrh/daily-retrospect-backend.git
          git stash || true
          git fetch origin prod
          git reset --hard origin/prod

          echo "${ENV_CONTENTS}" > .env

          pnpm install
          pnpm build
          pm2 restart ecosystem.config.js

          git remote set-url origin https://github.com/dnslfkrh/daily-retrospect-backend.git
          EOF
